name: Release Drafter

on:
  push:
    branches:
      - main  
  pull_request:
    types: [closed] 

jobs:
  update-release-draft:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release_drafter.yml  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
