name: release_drafter

on:
  workflow_dispatch:

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: .github/release_drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_assets:
    needs: draft_release
    runs-on: ubuntu-18.04
    steps:
      - name: Upload awesome-website.zip and DEPLOY.md
        run: |
          gh release upload "${{ github.ref_name }}" awesome-website.zip DEPLOY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
