name: release_drafter

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  draft_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config: |
            template: |
              ## Qué cambio

              $CHANGES

              ## Nueva fucninalidad

              $CONTRIBUTORS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticación

  upload_assets:
    needs: draft_release  # Depende del job draft_release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
