name: u3_tarea4

on:
  push:
    branches:
      - main  
    tags:
      - 'v*.*.*' 
  pull_request:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Build Hugo site
        run: |
          cd $GITHUB_WORKSPACE/u3_tarea4 
          chmod +x setup.sh 
          ./setup.sh 
          make build 

      - name: List files in public directory (for debugging)
        run: |
          ls -la $GITHUB_WORKSPACE/u3_tarea4/public  # Lista los archivos generados en la carpeta `public/` para depuración

      - name: Zip Hugo site
        run: |
          cd $GITHUB_WORKSPACE/u3_tarea4  
          zip -r tecnet-website.zip public/  

      - name: Create GitHub Release (only on tag push)
        if: startsWith(github.ref, 'refs/tags/') 
        id: create_release
        uses: softprops/action-gh-release@v1 
        with:
          tag_name: ${{ github.ref }}  
          name: ${{ github.ref_name }}  
          body: "Descripción de los cambios en esta versión. Incluye mejoras, correcciones y nuevas funcionalidades."
          files: |
            awesome-website.zip  # El archivo comprimido se incluye en el release
            DEPLOY.md  # Adjunta el archivo DEPLOY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
