name: u3_tarea4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Build Hugo site
        run: |
          cd $GITHUB_WORKSPACE/u3_tarea4 
          chmod +x setup.sh 
          ./setup.sh 
          make build 

      - name: List files in public directory (for debugging)
        run: |
          ls -la $GITHUB_WORKSPACE/u3_tarea4/public  # Lista los archivos generados en la carpeta `public/` para depuración

      - name: Zip Hugo site
        run: |
          cd $GITHUB_WORKSPACE/u3_tarea4  
          zip -r tecnet-website.zip public/  

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate PR
        run: echo "Validating PR"
