name: u3_tarea3

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # Se activa cuando se empuja una etiqueta con formato de versión (ej. v1.0.0)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Hugo site
        run: |
          cd $GITHUB_WORKSPACE/u3_tarea3
          chmod +x setup.sh 
          ./setup.sh
          make build  

      - name: Zip Hugo site
        run: zip -r tecnet-website.zip public/  # Comprime la carpeta `public`
        
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')  # Solo se ejecuta si se activa por una etiqueta
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          body_path: DEPLOY.md  # Usa el contenido de DEPLOY.md como descripción de la versión
          files: |
            tecnet-website.zip  # Añade el archivo comprimido a la versión

      - name: Upload artifact (non-tag trigger)
        if: "!startsWith(github.ref, 'refs/tags/')"  # Solo se ejecuta si no es una etiqueta
        uses: actions/upload-artifact@v4  # Actualizado a v4
        with:
          name: tecnet-website
          path: tecnet-website.zip
